@startuml

title Master Part Schema (partMaster.js)


class MasterPart{
{field}**Fields**
**//Immutable Properties//**
manufacturerPartNumber: String
brand: String
system: String
description: String
recommendedLubricant: String
fasteners: Object
userRating: Object
accuracyRating: Object
compatibleVehicles: Object
fitmentNotes: Object
failureNotes: Object


**//Cumulative Properties//**
userRating: Object
compatibleVehicles: Collection of Vehicles
fitmentNotes: Collection of Notes
failureNotes: Collection of Notes

{method}**Methods**
}


object recommendedTorque {
poundInches: Number
poundFeet: Number (12 times poundIncehs)
newtonMeters: Number
}


object userRating {
averageRating: Number
sumOfAllRatings: Number
countOfRatings: Number
}


object fasteners{
fastenerN: Object
fastenerN+1: Object
fastenerN+2: Object
...
}

object fastenerN {
 isPrevailingTorqueNut: Boolean
 recommendedThreadLocker: String
 isIncluded: Boolean
 torque: Object{}
 measures: Object{}
}

object torque {
  poundInches: Number
  poundFeet: Number
  newtonMeters: Number
}


object measures{
 system: String (Metric or SAE)
 external: Number
 thread: Number
 threadPitch: Number
}


object userRating {
 averageRating: Number,
 numberOfRatings: Number
}

object accuracyRating {
averageRating: Number,
 numberOfRatings: Number
}

object compatibleVehicles {

}

object fitmentNotes {
 collection of notes
}

object failureNotes {
 collection of notes
}




MasterPart ... recommendedTorque
MasterPart ... fasteners
fasteners ... fastenerN
fastenerN ... torque
fastenerN ... measures

MasterPart ---o userRating
MasterPart ---o accuracyRating
MasterPart ---o compatibleVehicles
MasterPart ---o fitmentNotes
MasterPart ---o failureNotes


note as N1
  accumulated from
  Replacement Parts
end note

note as N2
 accumulated from
 Repair Issues
end note

note as N3
 accumulated from
 Service Reports
end note

note as N4
 users input specially
end note


N1 -up-> userRating
N2 -up-> failureNotes
N3 -up-> fitmentNotes
N4 -up-> accuracyRating

@enduml