@startuml

title Master Part Schema (partMaster.js)


class MasterPart{
{field}**Fields**
**//Immutable Properties//**
brand: String
manufacturerPartNumber: String
system: String
requiresPrevailingTorqueNut: Boolean
replacementFastenersAreProvided: Boolean
recommendedLubricant: String
recommendedThreadLocker: String
recommendedTorque: Object{}

**//Cumulative Properties//**
userRating: Object
compatibleVehicles: Collection of Vehicles
fitmentNotes: Collection of Notes
failureNotes: Collection of Notes

{method}**Methods**
}


object recommendedTorque {
poundInches: Number
poundFeet: Number (12 times poundIncehs)
newtonMeters: Number
}


object userRating {
averageRating: Number
sumOfAllRatings: Number
countOfRatings: Number
}

MasterPart o-- userRating
MasterPart ... recommendedTorque


note as N1
  Ratings will be accumulated
  from user input of Replacement Part
end note
N1 -left-> userRating

@enduml