@startuml

class userProfile {
{field} <b>Fields</b>
name: Object[]
handle: String

{method}<b>Methods</b>
+some public method()
-some private method()
}

object name {
first: String
last: String
}

@enduml