@startuml

title  Vehicle Schema
class Vehicle {
{field} **Fields**
owner: ObjectId
vin: String
year: Number
make: String
model: String
color: String
engineDisplacement: Number
licensePlate: String
dateAcquired: Date
purchasePrice: Number
repairManual: Object{}

{method}**Methods**
+some public method()
-some private method()
}


object repairManual{
title : String
edition : String
publisher : String
}



note top
Assume user has one
primary repair manual
end note


repairManual -> Vehicle



@enduml