//Todo break this up into two classes as laid out in the UML partMaster and partReplacement
/*
* this plug in allows mongoose to extend schemas. May be useful for this feature
* https://github.com/briankircho/mongoose-schema-extend
*
*
 __________________REPLACEMENT PART______________________________
 * When a replacement part is added to a repair issue it MUST have access to a Master Part
 * When the replacement part is displayed to the user it will display data pulled from
 * the master part. To the end user it should appear as if they are a single object. To
 * the dev they should be distinct objects.
 
*  Mutable Properties - User input only
*  ----------------------------------------------------------
*  It should record where it was purchases
*  It should record the purchase price before tax
*  It should have a collection of Failure Notes
*    ("the rubber boot broke", "the rubber bushing wore out", "the temperature sensor went bad", "incorrect installation")


*
*  Mutable Properties - Autogenerated by Repair Issue
*   (Assumes part was previously recorded in a Service Record)
*  ----------------------------------------------------------
*  It should record the date of failure
*  It should the record the odometer reading at failure
*

*  Mutable Properties - Autogenerated by Service Record
*  ----------------------------------------------------------
*  It should record the date installed
*  It should the record the odometer reading at installation
*
**/